/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package southpark;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.MatteBorder;

/**
 *
 * @author PROGRAMACION
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        // Logo de la aplicación
        this.setIconImage(new ImageIcon(getClass().getResource("/southpark/images/cartman.png")).getImage());
        
        // Cargar fuente del cartel
        Font customFont = loadFont("./fonts/THUNDBIR.TTF", 55f);
        if (customFont != null) {
            textBotonJugar.setFont(customFont);
        }
        customFont = loadFont("./fonts/SOUTHPARK.ttf", 25f);
        if (customFont != null) {
            jLabelNick.setFont(customFont);
            jLabelName.setFont(customFont);
            jLabelAge.setFont(customFont);
            jLabelPass.setFont(customFont);
            jLabelNick1.setFont(customFont);
            jLabelName1.setFont(customFont);
            jLabelAge1.setFont(customFont);
            jLabelPass1.setFont(customFont);
        }
        // Fuente para el título
        customFont = loadFont("./fonts/SOUTHPARK.ttf", 50f);
        if(customFont != null) {
            jLabelTitulo.setFont(customFont);
            jLabelTituloSombra.setFont(customFont);
        }
        
        // Color transparente
        Color transparente=new Color(0,0,0,0);
        ContenedorFormulario.setBackground(transparente);
        ContenedorTitulo.setBackground(transparente);
        
        // Borde del botón
        MatteBorder bordeCartel=BorderFactory.createMatteBorder(0, 0, 2, 2, Color.BLACK);
        BotonJugar.setBorder(bordeCartel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelImagen1 = new jpanelimagen.JPanelImagen();
        ContenedorFormulario = new javax.swing.JPanel();
        jLabelNick = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelAge1 = new javax.swing.JLabel();
        jLabelNick1 = new javax.swing.JLabel();
        jLabelName1 = new javax.swing.JLabel();
        jLabelPass1 = new javax.swing.JLabel();
        BotonJugar = new javax.swing.JPanel();
        textBotonJugar = new javax.swing.JLabel();
        ContenedorTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTituloSombra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanelImagen1.setImagen(new jpanelimagen.ImagenFondo(new java.io.File("C:/Users/PROGRAMACION/Desktop/Interfaces-Swing/South Park/SouthPark/src/southpark/images/village-grande.jpg"), 1.0f));

        ContenedorFormulario.setLayout(new java.awt.GridBagLayout());

        jLabelNick.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNick.setText("NICK:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 4, 0);
        ContenedorFormulario.add(jLabelNick, gridBagConstraints);

        jLabelName.setForeground(new java.awt.Color(0, 0, 0));
        jLabelName.setText("NAME:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        ContenedorFormulario.add(jLabelName, gridBagConstraints);

        jLabelAge.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAge.setText("AGE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 4, 0);
        ContenedorFormulario.add(jLabelAge, gridBagConstraints);

        jLabelPass.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPass.setText("PASSWORD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 4, 32);
        ContenedorFormulario.add(jLabelPass, gridBagConstraints);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        ContenedorFormulario.add(jTextField1, gridBagConstraints);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        ContenedorFormulario.add(jTextField2, gridBagConstraints);

        jSpinner1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        ContenedorFormulario.add(jSpinner1, gridBagConstraints);

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        ContenedorFormulario.add(jPasswordField1, gridBagConstraints);

        jLabelAge1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAge1.setText("AGE:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        ContenedorFormulario.add(jLabelAge1, gridBagConstraints);

        jLabelNick1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNick1.setText("NICK:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        ContenedorFormulario.add(jLabelNick1, gridBagConstraints);

        jLabelName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName1.setText("NAME:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        ContenedorFormulario.add(jLabelName1, gridBagConstraints);

        jLabelPass1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPass1.setText("PASSWORD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 32);
        ContenedorFormulario.add(jLabelPass1, gridBagConstraints);

        BotonJugar.setBackground(new java.awt.Color(150, 107, 87));

        textBotonJugar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textBotonJugar.setForeground(new java.awt.Color(0, 0, 0));
        textBotonJugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBotonJugar.setText("P L A Y");
        textBotonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBotonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBotonJugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBotonJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBotonJugarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonJugarLayout = new javax.swing.GroupLayout(BotonJugar);
        BotonJugar.setLayout(BotonJugarLayout);
        BotonJugarLayout.setHorizontalGroup(
            BotonJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textBotonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        BotonJugarLayout.setVerticalGroup(
            BotonJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textBotonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        ContenedorTitulo.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("SOUTH PARK");
        ContenedorTitulo.add(jLabelTitulo);
        jLabelTitulo.setBounds(6, 9, 567, 60);

        jLabelTituloSombra.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTituloSombra.setForeground(new java.awt.Color(24, 24, 24));
        jLabelTituloSombra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloSombra.setText("SOUTH PARK");
        ContenedorTitulo.add(jLabelTituloSombra);
        jLabelTituloSombra.setBounds(10, 10, 567, 60);

        javax.swing.GroupLayout jPanelImagen1Layout = new javax.swing.GroupLayout(jPanelImagen1);
        jPanelImagen1.setLayout(jPanelImagen1Layout);
        jPanelImagen1Layout.setHorizontalGroup(
            jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagen1Layout.createSequentialGroup()
                .addComponent(ContenedorTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagen1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagen1Layout.createSequentialGroup()
                        .addComponent(BotonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagen1Layout.createSequentialGroup()
                        .addComponent(ContenedorFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        jPanelImagen1Layout.setVerticalGroup(
            jPanelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagen1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContenedorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BotonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // HOVER para el botón de jugar
    private void textBotonJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBotonJugarMouseEntered
        textBotonJugar.setForeground(new Color(220,220,220));
    }//GEN-LAST:event_textBotonJugarMouseEntered

    private void textBotonJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBotonJugarMouseExited
        textBotonJugar.setForeground(Color.BLACK);
    }//GEN-LAST:event_textBotonJugarMouseExited

    // Abrir el dialog al pulsar el botón
    private void textBotonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBotonJugarMouseClicked
        PantallaPersonajes dialog=new PantallaPersonajes(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_textBotonJugarMouseClicked

    // Método para cargar la fuente
    private Font loadFont(String path, float size) {
        try {
            InputStream fontStream = getClass().getResourceAsStream(path);
            Font font = Font.createFont(Font.TRUETYPE_FONT, fontStream);
            return font.deriveFont(size);
        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonJugar;
    private javax.swing.JPanel ContenedorFormulario;
    private javax.swing.JPanel ContenedorTitulo;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelAge1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelNick;
    private javax.swing.JLabel jLabelNick1;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPass1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloSombra;
    private jpanelimagen.JPanelImagen jPanelImagen1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel textBotonJugar;
    // End of variables declaration//GEN-END:variables
}
