/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad3ejercicio4;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Alfonso
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private Color colorDibujar;
    private int offsetX1;
    private int offsetY1;
    private int offsetX2;
    private int offsetY2;
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();   
        
        // Color transparente para los Contenedores de las bolas
        Color transparente=new Color(255,0,0,0);
        Figura1.setBackground(transparente);
        Figura2.setBackground(transparente);
        
        // Bordes para los TextFields
        MatteBorder bordeAbajo=BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY);
        jTextFieldFigura1.setBorder(bordeAbajo);
        jTextFieldFigura2.setBorder(bordeAbajo);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        VentanaMouseMove = new javax.swing.JPanel();
        ContenedorPintar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ContenedorColores = new javax.swing.JPanel();
        Rojo = new javax.swing.JPanel();
        Amarillo = new javax.swing.JPanel();
        Verde = new javax.swing.JPanel();
        Cian = new javax.swing.JPanel();
        Azul = new javax.swing.JPanel();
        Morado = new javax.swing.JPanel();
        Negro = new javax.swing.JPanel();
        VentanaMouseDrag = new javax.swing.JPanel();
        ContenedorTextFields = new javax.swing.JPanel();
        jTextFieldFigura1 = new javax.swing.JTextField();
        jTextFieldFigura2 = new javax.swing.JTextField();
        Figura1 = new javax.swing.JPanel();
        jLabelFigura1 = new javax.swing.JLabel();
        Bola1 = new javax.swing.JLabel();
        Figura2 = new javax.swing.JPanel();
        jLabelFigura2 = new javax.swing.JLabel();
        Bola2 = new javax.swing.JLabel();
        BotonInsertarNombre = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        VentanaMouseMove.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorPintar.setBackground(new java.awt.Color(246, 246, 246));
        ContenedorPintar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ContenedorPintar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ContenedorPintarMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout ContenedorPintarLayout = new javax.swing.GroupLayout(ContenedorPintar);
        ContenedorPintar.setLayout(ContenedorPintarLayout);
        ContenedorPintarLayout.setHorizontalGroup(
            ContenedorPintarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenedorPintarLayout.setVerticalGroup(
            ContenedorPintarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elije un color");

        ContenedorColores.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorColores.setLayout(new java.awt.GridBagLayout());

        Rojo.setBackground(new java.awt.Color(204, 0, 0));
        Rojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Rojo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RojoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RojoLayout = new javax.swing.GroupLayout(Rojo);
        Rojo.setLayout(RojoLayout);
        RojoLayout.setHorizontalGroup(
            RojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        RojoLayout.setVerticalGroup(
            RojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ContenedorColores.add(Rojo, gridBagConstraints);

        Amarillo.setBackground(new java.awt.Color(204, 204, 0));
        Amarillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Amarillo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AmarilloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AmarilloLayout = new javax.swing.GroupLayout(Amarillo);
        Amarillo.setLayout(AmarilloLayout);
        AmarilloLayout.setHorizontalGroup(
            AmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AmarilloLayout.setVerticalGroup(
            AmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ContenedorColores.add(Amarillo, gridBagConstraints);

        Verde.setBackground(new java.awt.Color(51, 204, 0));
        Verde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Verde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerdeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VerdeLayout = new javax.swing.GroupLayout(Verde);
        Verde.setLayout(VerdeLayout);
        VerdeLayout.setHorizontalGroup(
            VerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        VerdeLayout.setVerticalGroup(
            VerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ContenedorColores.add(Verde, gridBagConstraints);

        Cian.setBackground(new java.awt.Color(0, 153, 153));
        Cian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CianLayout = new javax.swing.GroupLayout(Cian);
        Cian.setLayout(CianLayout);
        CianLayout.setHorizontalGroup(
            CianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CianLayout.setVerticalGroup(
            CianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ContenedorColores.add(Cian, gridBagConstraints);

        Azul.setBackground(new java.awt.Color(0, 0, 153));
        Azul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Azul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AzulMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AzulLayout = new javax.swing.GroupLayout(Azul);
        Azul.setLayout(AzulLayout);
        AzulLayout.setHorizontalGroup(
            AzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AzulLayout.setVerticalGroup(
            AzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ContenedorColores.add(Azul, gridBagConstraints);

        Morado.setBackground(new java.awt.Color(102, 0, 102));
        Morado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Morado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Morado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoradoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MoradoLayout = new javax.swing.GroupLayout(Morado);
        Morado.setLayout(MoradoLayout);
        MoradoLayout.setHorizontalGroup(
            MoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MoradoLayout.setVerticalGroup(
            MoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        ContenedorColores.add(Morado, gridBagConstraints);

        Negro.setBackground(new java.awt.Color(0, 0, 0));
        Negro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Negro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NegroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NegroLayout = new javax.swing.GroupLayout(Negro);
        Negro.setLayout(NegroLayout);
        NegroLayout.setHorizontalGroup(
            NegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        NegroLayout.setVerticalGroup(
            NegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 23;
        ContenedorColores.add(Negro, gridBagConstraints);

        javax.swing.GroupLayout VentanaMouseMoveLayout = new javax.swing.GroupLayout(VentanaMouseMove);
        VentanaMouseMove.setLayout(VentanaMouseMoveLayout);
        VentanaMouseMoveLayout.setHorizontalGroup(
            VentanaMouseMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMouseMoveLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(VentanaMouseMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ContenedorPintar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenedorColores, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(VentanaMouseMoveLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        VentanaMouseMoveLayout.setVerticalGroup(
            VentanaMouseMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMouseMoveLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContenedorColores, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ContenedorPintar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jTabbedPane.addTab("Pinturillo", VentanaMouseMove);

        VentanaMouseDrag.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorTextFields.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTextFields.setLayout(new java.awt.GridBagLayout());

        jTextFieldFigura1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldFigura1.setText("Nombre figura 1...");
        jTextFieldFigura1.setBorder(null);
        jTextFieldFigura1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFigura1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFigura1FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 220;
        ContenedorTextFields.add(jTextFieldFigura1, gridBagConstraints);

        jTextFieldFigura2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldFigura2.setText("Nombre figura 2...");
        jTextFieldFigura2.setBorder(null);
        jTextFieldFigura2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFigura2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFigura2FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        ContenedorTextFields.add(jTextFieldFigura2, gridBagConstraints);

        Figura1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Figura1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Figura1MouseDragged(evt);
            }
        });
        Figura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Figura1MousePressed(evt);
            }
        });

        jLabelFigura1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabelFigura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFigura1.setText("Nombre figura 1");

        Bola1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bola1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3ejercicio4/images/Circulo.png"))); // NOI18N

        javax.swing.GroupLayout Figura1Layout = new javax.swing.GroupLayout(Figura1);
        Figura1.setLayout(Figura1Layout);
        Figura1Layout.setHorizontalGroup(
            Figura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFigura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Figura1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Bola1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Figura1Layout.setVerticalGroup(
            Figura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFigura1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bola1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Figura2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Figura2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Figura2MouseDragged(evt);
            }
        });
        Figura2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Figura2MousePressed(evt);
            }
        });

        jLabelFigura2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabelFigura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFigura2.setText("Nombre figura 2");

        Bola2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bola2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad3ejercicio4/images/Circulo-azul.png"))); // NOI18N

        javax.swing.GroupLayout Figura2Layout = new javax.swing.GroupLayout(Figura2);
        Figura2.setLayout(Figura2Layout);
        Figura2Layout.setHorizontalGroup(
            Figura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Figura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bola2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFigura2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
        );
        Figura2Layout.setVerticalGroup(
            Figura2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Figura2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFigura2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bola2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BotonInsertarNombre.setBackground(new java.awt.Color(0, 153, 204));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INSERTAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonInsertarNombreLayout = new javax.swing.GroupLayout(BotonInsertarNombre);
        BotonInsertarNombre.setLayout(BotonInsertarNombreLayout);
        BotonInsertarNombreLayout.setHorizontalGroup(
            BotonInsertarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        BotonInsertarNombreLayout.setVerticalGroup(
            BotonInsertarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout VentanaMouseDragLayout = new javax.swing.GroupLayout(VentanaMouseDrag);
        VentanaMouseDrag.setLayout(VentanaMouseDragLayout);
        VentanaMouseDragLayout.setHorizontalGroup(
            VentanaMouseDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaMouseDragLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonInsertarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(VentanaMouseDragLayout.createSequentialGroup()
                .addGroup(VentanaMouseDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaMouseDragLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Figura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Figura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaMouseDragLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(ContenedorTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        VentanaMouseDragLayout.setVerticalGroup(
            VentanaMouseDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMouseDragLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ContenedorTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonInsertarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(VentanaMouseDragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Figura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Figura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        jTabbedPane.addTab("Mover elementos", VentanaMouseDrag);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContenedorPintarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContenedorPintarMouseMoved
            Graphics g = ContenedorPintar.getGraphics();
            g.setColor(colorDibujar);
            g.fillRect(evt.getX(), evt.getY(), 5, 5);
    }//GEN-LAST:event_ContenedorPintarMouseMoved

    // CLICK LSITENER DE TODOS LOS COLORES
    private void AmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmarilloMouseClicked
        colorDibujar=new Color(204,204,0);
    }//GEN-LAST:event_AmarilloMouseClicked

    private void RojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RojoMouseClicked
        colorDibujar=new Color(204,0,0);
    }//GEN-LAST:event_RojoMouseClicked

    private void VerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerdeMouseClicked
        colorDibujar=new Color(51,204,0);
    }//GEN-LAST:event_VerdeMouseClicked

    private void CianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CianMouseClicked
        colorDibujar=new Color(0,153,153);
    }//GEN-LAST:event_CianMouseClicked

    private void AzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AzulMouseClicked
        colorDibujar=new Color(0,0,153);
    }//GEN-LAST:event_AzulMouseClicked

    private void MoradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoradoMouseClicked
        colorDibujar=new Color(102,0,102);
    }//GEN-LAST:event_MoradoMouseClicked

    private void NegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NegroMouseClicked
        colorDibujar=new Color(0,0,0);
    }//GEN-LAST:event_NegroMouseClicked

    // PLACEHOLDERS
    private void jTextFieldFigura1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFigura1FocusGained
        String texto=jTextFieldFigura1.getText();
        if(texto.equals("Nombre figura 1...")) {
            jTextFieldFigura1.setText("");       
            jTextFieldFigura1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldFigura1FocusGained

    private void jTextFieldFigura1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFigura1FocusLost
        String texto=jTextFieldFigura1.getText();
        if(texto.equals("")) {
            jTextFieldFigura1.setText("Nombre figura 1...");
            jTextFieldFigura1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldFigura1FocusLost

    private void jTextFieldFigura2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFigura2FocusGained
        String texto=jTextFieldFigura2.getText();
        if(texto.equals("Nombre figura 2...")) {
            jTextFieldFigura2.setText("");       
            jTextFieldFigura2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldFigura2FocusGained

    private void jTextFieldFigura2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFigura2FocusLost
        String texto=jTextFieldFigura2.getText();
        if(texto.equals("")) {
            jTextFieldFigura2.setText("Nombre figura 2...");
            jTextFieldFigura2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldFigura2FocusLost

    // CAMBIAR EL NOMBRE DE LOS CÍRCULOS AL HACER CLICK
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String n1=jTextFieldFigura1.getText();
        String n2=jTextFieldFigura2.getText();
        
        if(!n1.equals("") && !n1.equals("Nombre figura 1...") && !n2.equals("") && !n2.equals("Nombre figura 2...")) {
            jLabelFigura1.setText(n1);
            jLabelFigura2.setText(n2);
            
            VentanaMouseDrag.repaint();
            VentanaMouseDrag.revalidate();
        } else {
            JOptionPane.showMessageDialog(this, "Rellena los dos campos");
        }
                
    }//GEN-LAST:event_jLabel6MouseClicked

    // HOVER DEL BOTÓN
    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        BotonInsertarNombre.setBackground(new Color(6, 116, 153));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        BotonInsertarNombre.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_jLabel6MouseExited

    // Listeners para poder mover las bolas
    private void Figura1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Figura1MousePressed
        offsetX1=evt.getX();
        offsetY1=evt.getY();
    }//GEN-LAST:event_Figura1MousePressed

    private void Figura1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Figura1MouseDragged
        int x=evt.getXOnScreen()-offsetX1-Figura1.getWidth();
        int y=evt.getYOnScreen()-offsetY1-Figura1.getHeight();
        
        Figura1.setLocation(x, y);
    }//GEN-LAST:event_Figura1MouseDragged

    private void Figura2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Figura2MousePressed
        offsetX2=evt.getX();
        offsetY2=evt.getY();
    }//GEN-LAST:event_Figura2MousePressed

    private void Figura2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Figura2MouseDragged
        int x=evt.getXOnScreen()-offsetX2-Figura2.getWidth();
        int y=evt.getYOnScreen()-offsetY2-Figura2.getHeight();
        
        Figura2.setLocation(x, y);
    }//GEN-LAST:event_Figura2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Amarillo;
    private javax.swing.JPanel Azul;
    private javax.swing.JLabel Bola1;
    private javax.swing.JLabel Bola2;
    private javax.swing.JPanel BotonInsertarNombre;
    private javax.swing.JPanel Cian;
    private javax.swing.JPanel ContenedorColores;
    private javax.swing.JPanel ContenedorPintar;
    private javax.swing.JPanel ContenedorTextFields;
    private javax.swing.JPanel Figura1;
    private javax.swing.JPanel Figura2;
    private javax.swing.JPanel Morado;
    private javax.swing.JPanel Negro;
    private javax.swing.JPanel Rojo;
    private javax.swing.JPanel VentanaMouseDrag;
    private javax.swing.JPanel VentanaMouseMove;
    private javax.swing.JPanel Verde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFigura1;
    private javax.swing.JLabel jLabelFigura2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldFigura1;
    private javax.swing.JTextField jTextFieldFigura2;
    // End of variables declaration//GEN-END:variables
}
