/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad4interfaz.pantallas;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author Alfonso
 */
public class JuegoPPT extends javax.swing.JDialog {

    Border bordeActivo=BorderFactory.createLineBorder(Color.WHITE, 2);
    int valor;
    /**
     * Creates new form JuegoPPT
     */
    public JuegoPPT(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Estilos de ventana
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/actividad4interfaz/images/icono.png")).getImage());               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorGeneral = new javax.swing.JPanel();
        BotonReset = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotonPiedra = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BotonPapel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BotonTijeras = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCPU = new javax.swing.JLabel();
        jLabelJugador = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ContenedorGeneral.setBackground(new java.awt.Color(18, 18, 18));
        ContenedorGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonReset.setBackground(new java.awt.Color(43, 43, 43));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 235, 235));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESET");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonResetLayout = new javax.swing.GroupLayout(BotonReset);
        BotonReset.setLayout(BotonResetLayout);
        BotonResetLayout.setHorizontalGroup(
            BotonResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        BotonResetLayout.setVerticalGroup(
            BotonResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        ContenedorGeneral.add(BotonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 150, 60));

        BotonPiedra.setBackground(new java.awt.Color(86, 86, 86));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 235, 235));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PIEDRA");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonPiedraLayout = new javax.swing.GroupLayout(BotonPiedra);
        BotonPiedra.setLayout(BotonPiedraLayout);
        BotonPiedraLayout.setHorizontalGroup(
            BotonPiedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BotonPiedraLayout.setVerticalGroup(
            BotonPiedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ContenedorGeneral.add(BotonPiedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 50));

        BotonPapel.setBackground(new java.awt.Color(86, 86, 86));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 235, 235));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PAPEL");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonPapelLayout = new javax.swing.GroupLayout(BotonPapel);
        BotonPapel.setLayout(BotonPapelLayout);
        BotonPapelLayout.setHorizontalGroup(
            BotonPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        BotonPapelLayout.setVerticalGroup(
            BotonPapelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ContenedorGeneral.add(BotonPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, -1));

        BotonTijeras.setBackground(new java.awt.Color(86, 86, 86));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 235, 235));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TIJERAS");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BotonTijerasLayout = new javax.swing.GroupLayout(BotonTijeras);
        BotonTijeras.setLayout(BotonTijerasLayout);
        BotonTijerasLayout.setHorizontalGroup(
            BotonTijerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        BotonTijerasLayout.setVerticalGroup(
            BotonTijerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        ContenedorGeneral.add(BotonTijeras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jLabelCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContenedorGeneral.add(jLabelCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, 100));

        jLabelJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContenedorGeneral.add(jLabelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 100));
        ContenedorGeneral.add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 510, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        BotonPiedra.setBorder(bordeActivo);
        BotonPapel.setBorder(null);
        BotonTijeras.setBorder(null);
        
        jLabelJugador.setText("PIEDRA");
        valor=1;
        comenzarJuego(valor);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        BotonPiedra.setBorder(null);
        BotonPapel.setBorder(bordeActivo);
        BotonTijeras.setBorder(null);
        
        
        jLabelJugador.setText("PAPEL");
        valor=2;
        comenzarJuego(valor);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        BotonPiedra.setBorder(null);
        BotonPapel.setBorder(null);
        BotonTijeras.setBorder(bordeActivo);
        
        jLabelJugador.setText("TIJERA");
        valor=3;
        comenzarJuego(valor);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        BotonPiedra.setBorder(null);
        BotonPapel.setBorder(null);
        BotonTijeras.setBorder(null);
    }//GEN-LAST:event_jLabel3MouseClicked

    public void comenzarJuego(int valor) {
        int cpu=(int) (1+Math.random()*3);
        
        if(cpu==1) {
            jLabelCPU.setText("PIEDRA");
        } else if(cpu == 2) {
            jLabelCPU.setText("PAPEL");
        } else if(cpu == 3) {
            jLabelCPU.setText("TIJERA");
        }                
        
        if(valor == cpu) {
            jLabelResultado.setText("EMPATE");
        } else if((valor == 1 && cpu == 2) || (valor == 2 && cpu == 3) || (valor == 3 && cpu == 1)) {
            jLabelResultado.setText("HAS PERDIDO");
        } else {
            jLabelResultado.setText("HAS GANADO");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonPapel;
    private javax.swing.JPanel BotonPiedra;
    private javax.swing.JPanel BotonReset;
    private javax.swing.JPanel BotonTijeras;
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCPU;
    private javax.swing.JLabel jLabelJugador;
    private javax.swing.JLabel jLabelResultado;
    // End of variables declaration//GEN-END:variables
}
