/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad4interfaz.pantallas;

import actividad4interfaz.pantallas.Fuente;
import actividad4interfaz.pantallas.Fuente;
import actividad4interfaz.pantallas.SeleccionJuego;
import actividad4interfaz.pantallas.SeleccionJuego;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Alfonso
 */
public class PantallaRegistro extends javax.swing.JFrame {

    CompoundBorder bordeCompuesto;
    CompoundBorder bordeCompuestoFinal;
    MatteBorder bordeExteriorFinal;
    MatteBorder bordeExterior;
    MatteBorder bordeInterno;
    AudioClip change;
    AudioClip audio;
    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRegistro() {
        initComponents();
        
        // Estilos de la pantalla 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(550, 410);
        this.setIconImage(new ImageIcon(getClass().getResource("/actividad4interfaz/images/icono.png")).getImage());
        
        // Estilos del formulario
        Color transparente=new Color(0,0,0,0);
        Formulario.setOpaque(false);
        
        // Fuente
        Fuente cambiarFuente=new Fuente();
        Font fuente=cambiarFuente.cargarFuente("/actividad4interfaz/fonts/Roboto-Thin.ttf", 30f);
        if(fuente != null){
            LabelBotonJugar.setFont(fuente);
        }
        BotonEntrar.setBackground(transparente);
        BotonEntrar.setOpaque(false);
        BotonEntrar.requestFocusInWindow();
        
        // Borde del botón
        bordeInterno=BorderFactory.createMatteBorder(1, 0, 1, 0, new Color(255, 25, 0));
        bordeExterior=BorderFactory.createMatteBorder(2, 0, 2, 0, new Color(255, 25, 0, 70));
        bordeExteriorFinal=BorderFactory.createMatteBorder(4, 0, 4, 0, new Color(255, 25, 0, 15));
        bordeCompuesto=new CompoundBorder(bordeExterior, bordeInterno);
        bordeCompuestoFinal=new CompoundBorder(bordeExteriorFinal, bordeCompuesto);
        
        // Bordes para el padding
        EmptyBorder paddingIzquierda=(EmptyBorder) BorderFactory.createEmptyBorder(0,10,0,0);
        Border bordeComun=BorderFactory.createLineBorder(new Color(102,102,102), 1);
        CompoundBorder bordeTextfields=BorderFactory.createCompoundBorder(bordeComun, paddingIzquierda);
        jTextFieldEmail.setBorder(bordeTextfields);
        jTextFieldUsuario.setBorder(bordeTextfields);
        jPasswordFieldContra.setBorder(bordeTextfields);
        
        audio=java.applet.Applet.newAudioClip(getClass().getResource("/actividad4interfaz/audio/play.wav"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ContenedorGeneral = new javax.swing.JPanel();
        Formulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldContra = new javax.swing.JPasswordField();
        MostrarOcultar = new javax.swing.JCheckBox();
        BotonEntrar = new javax.swing.JPanel();
        LabelBotonJugar = new javax.swing.JLabel();
        LabelRegistro = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenedorGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Formulario.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 234, 234));
        jLabel1.setText("USUARIO:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 12;
        Formulario.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 234, 234));
        jLabel2.setText("EMAIL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 12;
        Formulario.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 234, 234));
        jLabel3.setText("CONTRASEÑA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.ipady = 17;
        Formulario.add(jLabel3, gridBagConstraints);

        jTextFieldUsuario.setBackground(new java.awt.Color(27, 27, 27));
        jTextFieldUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setText("NOMBRE DE USUARIO...");
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 229;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        Formulario.add(jTextFieldUsuario, gridBagConstraints);

        jTextFieldEmail.setBackground(new java.awt.Color(27, 27, 27));
        jTextFieldEmail.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmail.setText("DIRECCIÓN DE EMAIL...");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        Formulario.add(jTextFieldEmail, gridBagConstraints);

        jPasswordFieldContra.setBackground(new java.awt.Color(27, 27, 27));
        jPasswordFieldContra.setForeground(new java.awt.Color(231, 231, 231));
        jPasswordFieldContra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        Formulario.add(jPasswordFieldContra, gridBagConstraints);

        MostrarOcultar.setOpaque(false);
        MostrarOcultar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MostrarOcultarStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        Formulario.add(MostrarOcultar, gridBagConstraints);

        ContenedorGeneral.add(Formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 470, 150));

        BotonEntrar.setBackground(new java.awt.Color(13, 13, 13));

        LabelBotonJugar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LabelBotonJugar.setForeground(new java.awt.Color(255, 25, 0));
        LabelBotonJugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBotonJugar.setText("ENTRAR");
        LabelBotonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelBotonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBotonJugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelBotonJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelBotonJugarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonEntrarLayout = new javax.swing.GroupLayout(BotonEntrar);
        BotonEntrar.setLayout(BotonEntrarLayout);
        BotonEntrarLayout.setHorizontalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelBotonJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BotonEntrarLayout.setVerticalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelBotonJugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ContenedorGeneral.add(BotonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, 60));

        LabelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4interfaz/images/registro.png"))); // NOI18N
        ContenedorGeneral.add(LabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 430, 100));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actividad4interfaz/images/fondo1.png"))); // NOI18N
        ContenedorGeneral.add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ABRIR NUEVA PESTAÑA, VERIFICAR VALORES
    private void LabelBotonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBotonJugarMouseClicked
        String nombre=jTextFieldUsuario.getText();
        String email=jTextFieldEmail.getText();
        char[] contra=jPasswordFieldContra.getPassword();
        String contraFinal=String.valueOf(contra);
        
        if(!nombre.equals("") && !nombre.equals("") && !contraFinal.equals("") && !email.equals("DIRECCIÓN DE EMAIL...") &&!nombre.equals("NOMBRE DE USUARIO...")) {
            if(esEmail(email)) {
                audio.play();
                SeleccionJuego s=new SeleccionJuego(nombre, email);
                s.setVisible(true);
        
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El email no es válido","Email no válido",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos","Campos vacíos",JOptionPane.ERROR_MESSAGE);
        }                
    }//GEN-LAST:event_LabelBotonJugarMouseClicked

    // VERIFICAR QUE EL EMAIL ES VÁLIDO
    private boolean esEmail(String email) {
        return email.matches("[a-zA-Z0-9_.%]+@[a-zA-Z]+\\.[a-zA-Z]+");
    }
    
    private void LabelBotonJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBotonJugarMouseEntered
        ContenedorGeneral.repaint();
        ContenedorGeneral.revalidate();
        BotonEntrar.setBorder(bordeCompuestoFinal);
    }//GEN-LAST:event_LabelBotonJugarMouseEntered

    private void LabelBotonJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBotonJugarMouseExited
        ContenedorGeneral.repaint();
        ContenedorGeneral.revalidate();
        BotonEntrar.setBorder(null);
    }//GEN-LAST:event_LabelBotonJugarMouseExited

    // PLACEHOLDERS PARA EL USUARIO Y EL EMAIL
    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        String texto=jTextFieldUsuario.getText();
               
        if(texto.equals("NOMBRE DE USUARIO...")) {
            jTextFieldUsuario.setText("");
            jTextFieldUsuario.setForeground(new Color(231,231,231));
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        String texto=jTextFieldUsuario.getText();
        
        if(texto.equals("")) {
            jTextFieldUsuario.setText("NOMBRE DE USUARIO...");
            jTextFieldUsuario.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        String texto=jTextFieldEmail.getText();
        
        if(texto.equals("DIRECCIÓN DE EMAIL...")) {
            jTextFieldEmail.setText("");
            jTextFieldEmail.setForeground(new Color(231,231,231));
        }
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        String texto=jTextFieldEmail.getText();
        
        if(texto.equals("")) {
            jTextFieldEmail.setText("DIRECCIÓN DE EMAIL...");
            jTextFieldEmail.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    // Botón para ocultar y mostrar contraseña
    private void MostrarOcultarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MostrarOcultarStateChanged
        if(MostrarOcultar.isSelected()) {
            jPasswordFieldContra.setEchoChar((char)0);
        } else {
            jPasswordFieldContra.setEchoChar('*');
            jPasswordFieldContra.setForeground(new Color(231, 231, 231));
        }
    }//GEN-LAST:event_MostrarOcultarStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonEntrar;
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JPanel Formulario;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel LabelBotonJugar;
    private javax.swing.JLabel LabelRegistro;
    private javax.swing.JCheckBox MostrarOcultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordFieldContra;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
