/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegobolacolisiones;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Alfonso
 */
public class ColisionesEfecto extends javax.swing.JFrame {

    private int x,y;
    private int calcX, calcY;
    /**
     * Creates new form ColisionesEfecto
     */
    public ColisionesEfecto() {
        initComponents();
        
        // Estilos del Frame
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);        
        this.setIconImage(new ImageIcon(getClass().getResource("/juegobolacolisiones/images/dvd.png")).getImage());
        
        // Inicializar variables
        calcX=2;
        calcY=2;
        x=DVD.getX();
        y=DVD.getX();
        
        Timer timer=new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                DVD.setLocation(x, y);
                
                if((DVD.getY()+DVD.getHeight()) >= ContenedorGeneral.getHeight()) {
                    calcY=-2;                   
                }
                if((DVD.getX()+DVD.getWidth()) >= ContenedorGeneral.getWidth()) {
                    calcX=-2;     
                }
                if(DVD.getY() == 0) {
                    calcY=2;                   
                }
                if(DVD.getX() == 0) {
                    calcX=2;     
                }
                
                x+=calcX;
                y+=calcY;                               
            }
        });
        timer.start();                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorGeneral = new javax.swing.JPanel();
        DVD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(615, 410));

        ContenedorGeneral.setBackground(new java.awt.Color(0, 0, 0));
        ContenedorGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DVD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegobolacolisiones/images/dvd70.png"))); // NOI18N
        ContenedorGeneral.add(DVD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColisionesEfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColisionesEfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColisionesEfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColisionesEfecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColisionesEfecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JLabel DVD;
    // End of variables declaration//GEN-END:variables
}
