/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1trimestre.pantallas;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Alfonso
 */
public class DialogProveedores extends javax.swing.JDialog {

    ArrayList<Proveedor> proveedores;
    /**
     * Creates new form DialogProveedores
     */
    public DialogProveedores(java.awt.Frame parent, boolean modal, ArrayList<Proveedor> proveedores) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        // ArrayLisr heredado del JFrame
        this.proveedores=proveedores;    
        
        // Bordes de los jTextField
        MatteBorder bordeBajo=BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(174,71,213));
        jTextFieldCiudad.setBorder(bordeBajo);
        jTextFieldDireccion.setBorder(bordeBajo);
        jTextFieldEmpresa.setBorder(bordeBajo);
        jTextFieldNIT.setBorder(bordeBajo);
        jTextFieldTelefono.setBorder(bordeBajo);
        
        //imagenesCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ContenedorGeneral = new javax.swing.JPanel();
        ContenedorFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNIT = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        BotonVaciar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ContenedorGeneral.setBackground(new java.awt.Color(255, 255, 255));

        ContenedorFormulario.setOpaque(false);
        ContenedorFormulario.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 71, 213));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 88;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        ContenedorFormulario.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 71, 213));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        ContenedorFormulario.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(174, 71, 213));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 14, 0);
        ContenedorFormulario.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(174, 71, 213));
        jLabel4.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        ContenedorFormulario.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(174, 71, 213));
        jLabel5.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 13, 0);
        ContenedorFormulario.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(174, 71, 213));
        jLabel6.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel6.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 13, 0);
        ContenedorFormulario.add(jLabel6, gridBagConstraints);

        jTextFieldNIT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNIT.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldNIT.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jTextFieldNIT.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        ContenedorFormulario.add(jTextFieldNIT, gridBagConstraints);

        jTextFieldDireccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDireccion.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDireccion.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jTextFieldDireccion.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        ContenedorFormulario.add(jTextFieldDireccion, gridBagConstraints);

        jTextFieldTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldTelefono.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jTextFieldTelefono.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        ContenedorFormulario.add(jTextFieldTelefono, gridBagConstraints);

        jTextFieldCiudad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldCiudad.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldCiudad.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jTextFieldCiudad.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        ContenedorFormulario.add(jTextFieldCiudad, gridBagConstraints);

        jTextFieldEmpresa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmpresa.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jTextFieldEmpresa.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        ContenedorFormulario.add(jTextFieldEmpresa, gridBagConstraints);

        jComboBox.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "España", "Argentina", "México", "EEUU", "Japón" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        ContenedorFormulario.add(jComboBox, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen1trimestre/images/rocket.png"))); // NOI18N
        jLabel7.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel7.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(174, 71, 213));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel8.text")); // NOI18N

        BotonAgregar.setBackground(new java.awt.Color(174, 71, 213));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen1trimestre/images/agregar.png"))); // NOI18N
        jLabel9.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel9.text")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonAgregarLayout = new javax.swing.GroupLayout(BotonAgregar);
        BotonAgregar.setLayout(BotonAgregarLayout);
        BotonAgregarLayout.setHorizontalGroup(
            BotonAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        BotonAgregarLayout.setVerticalGroup(
            BotonAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        BotonVaciar.setBackground(new java.awt.Color(174, 71, 213));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen1trimestre/images/vaciar.png"))); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(DialogProveedores.class, "DialogProveedores.jLabel10.text")); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonVaciarLayout = new javax.swing.GroupLayout(BotonVaciar);
        BotonVaciar.setLayout(BotonVaciarLayout);
        BotonVaciarLayout.setHorizontalGroup(
            BotonVaciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        BotonVaciarLayout.setVerticalGroup(
            BotonVaciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContenedorGeneralLayout = new javax.swing.GroupLayout(ContenedorGeneral);
        ContenedorGeneral.setLayout(ContenedorGeneralLayout);
        ContenedorGeneralLayout.setHorizontalGroup(
            ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ContenedorFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(32, 32, 32))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContenedorGeneralLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(BotonVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContenedorGeneralLayout.setVerticalGroup(
            ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorGeneralLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(ContenedorFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ContenedorGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonVaciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // HOVER DE LSO BOTONES
    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        jTextFieldCiudad.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldNIT.setText("");
        jTextFieldTelefono.setText("");
        jComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        String ciudad=jTextFieldCiudad.getText();
        String direccion=jTextFieldDireccion.getText();
        String empresa=jTextFieldEmpresa.getText();
        String nit=jTextFieldNIT.getText();
        String telefono=jTextFieldTelefono.getText();
        String pais="";
                
        // Switch case para ver que valor se ha seleccionado
        switch(jComboBox.getSelectedIndex()) {
            case 0:
                pais="España";
                break;
            case 1:
                pais="Argentina";
                break;
            case 2:
                pais="México";
                break;
            case 3:
                pais="EEUU";
                break;
            case 4:
                pais="Japón";
                break;                    
        }
                    
        if(ciudad == null || direccion == null ||empresa == null || nit == null || telefono == null || ciudad.equals("") || direccion.equals("") || empresa.equals("") || nit.equals("") || telefono.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "Campos vacíos", JOptionPane.ERROR_MESSAGE);
        
        } else {
            if(!esNIT(nit)) {
                JOptionPane.showMessageDialog(this, "NIT no válido.Debe contener 9 números", "NIT no válido", JOptionPane.ERROR_MESSAGE);    
            } else if(soloLetras(ciudad)) {
                JOptionPane.showMessageDialog(this, "La ciudad no puede contener números", "Ciudad no válida", JOptionPane.ERROR_MESSAGE);    
            } else if(!esNIT(nit)) {
                JOptionPane.showMessageDialog(this, "Teléfono no válido", "Teléfono no válido", JOptionPane.ERROR_MESSAGE);    
            } else {
                Proveedor pro=new Proveedor(nit, direccion, empresa, telefono, ciudad, pais);                
                proveedores.add(pro);

                dispose();
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private boolean esNIT(String nit) {
        return nit.matches("[0-9]{9}");
    }
    
    // Para verificar la ciudad
    private boolean soloLetras(String texto) {
        return texto.matches("[0-9]+");
    }
    
    
    public void imagenesCombo() {
        DefaultComboBoxModel<String> mode=new DefaultComboBoxModel();
        mode.addElement("España");
        mode.addElement("Argentina");
        mode.addElement("México");
        mode.addElement("EEUU");
        mode.addElement("Japón");
        
        jComboBox.setModel(mode);
        jComboBox.setRenderer(new ListCellRenderer<String>() {
            @Override
            public Component getListCellRendererComponent(JList<? extends String> jlist, String value, int index, boolean isSelected, boolean bln1) {
                JLabel label=new JLabel();                
                switch(value) {
                    case "España":
                        label.setIcon(new ImageIcon(getClass().getResource("images/spain.png")));
                        label.setText("España");
                        break;
                    case "Argentina":
                        label.setIcon(new ImageIcon(getClass().getResource("images/argentina.png")));
                        label.setText("Argentina");
                        break;
                    case "México":
                        label.setIcon(new ImageIcon(getClass().getResource("images/mexico.png")));
                        label.setText("México");
                        break;
                    case "EEUU":
                        label.setIcon(new ImageIcon(getClass().getResource("images/eeuu.png")));
                        label.setText("EEUU");
                        break;
                    case "Japón":
                        label.setIcon(new ImageIcon(getClass().getResource("images/japon.png")));
                        label.setText("Japón");
                        break;
                }
                
                if(isSelected) {
                    label.setBackground(jlist.getSelectionBackground());
                    label.setOpaque(true);
                }
                
                return label;
            }            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonAgregar;
    private javax.swing.JPanel BotonVaciar;
    private javax.swing.JPanel ContenedorFormulario;
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldNIT;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
