/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1trimestre.pantallas;

import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Alfonso
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        // Estilos del JFrame
        this.setIconImage(new ImageIcon(getClass().getResource("/examen1trimestre/images/icono.png")).getImage());
        this.setResizable(false);
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);
        this.setTitle("INICIO DE SESIÓN");
        
        // poner imagen en el jPanel
        String rutaImagen="/Examen1Trimestre/src/examen1trimestre/images/logoBlanco.png";
        jPanelImagenLogo.setImagen(new jpanelimagen.ImagenFondo(new File(rutaImagen), 1.0f));        
        
        // Bordes de los jTextField
        MatteBorder bordeBajo=BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(174,71,213));
        jTextFieldUsuario.setBorder(bordeBajo);
        jPasswordFieldContra.setBorder(bordeBajo);
        
        BotonEntrar.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorGeneral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelImagenLogo = new jpanelimagen.JPanelImagen();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContra = new javax.swing.JPasswordField();
        BotonEntrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenedorGeneral.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(174, 71, 213));

        jPanelImagenLogo.setImagen(new jpanelimagen.ImagenFondo(new java.io.File("C:/Users/PROGRAMACION/Desktop/rincon_cuerva_alfonso/Examen1Trimestre/src/examen1trimestre/images/logoBlanco.png"), 0.5f));
        jPanelImagenLogo.setOpaque(false);

        javax.swing.GroupLayout jPanelImagenLogoLayout = new javax.swing.GroupLayout(jPanelImagenLogo);
        jPanelImagenLogo.setLayout(jPanelImagenLogoLayout);
        jPanelImagenLogoLayout.setHorizontalGroup(
            jPanelImagenLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelImagenLogoLayout.setVerticalGroup(
            jPanelImagenLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanelImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanelImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        ContenedorGeneral.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 420));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 71, 213));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIO DE SESIÓN");
        ContenedorGeneral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 390, 80));

        jTextFieldUsuario.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setText("Inserta tu usuario");
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        ContenedorGeneral.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 310, 40));

        jPasswordFieldContra.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPasswordFieldContra.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordFieldContra.setText("INSERTAR");
        jPasswordFieldContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraFocusLost(evt);
            }
        });
        ContenedorGeneral.add(jPasswordFieldContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 310, 40));

        BotonEntrar.setBackground(new java.awt.Color(174, 71, 213));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRAR");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonEntrarLayout = new javax.swing.GroupLayout(BotonEntrar);
        BotonEntrar.setLayout(BotonEntrarLayout);
        BotonEntrarLayout.setHorizontalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        BotonEntrarLayout.setVerticalGroup(
            BotonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        ContenedorGeneral.add(BotonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 130, 60));

        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Mostrar contraseña");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        ContenedorGeneral.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // PLACEHOLDER DE LOS JTEXTFIELD
    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        String texto=jTextFieldUsuario.getText();
        
        if(texto.equals("Inserta tu usuario")) {
            jTextFieldUsuario.setText("");
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        String texto=jTextFieldUsuario.getText();
        
        if(texto.equals("")) {
            jTextFieldUsuario.setText("Inserta tu usuario");
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if(jCheckBox1.isSelected()) {
            jPasswordFieldContra.setEchoChar((char)0);
        } else {
            jPasswordFieldContra.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jPasswordFieldContraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraFocusGained
        String texto=new String(jPasswordFieldContra.getPassword());
        
        if(texto.equals("INSERTAR")) {
            jPasswordFieldContra.setText("");
        }
    }//GEN-LAST:event_jPasswordFieldContraFocusGained

    private void jPasswordFieldContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraFocusLost
        String texto=new String(jPasswordFieldContra.getPassword());
        
        if(texto.equals("")) {
            jPasswordFieldContra.setText("INSERTAR");
        }
    }//GEN-LAST:event_jPasswordFieldContraFocusLost

    // HOVER DEL BOTÓN
    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        BotonEntrar.setBackground(new Color(131, 53, 161));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        BotonEntrar.setBackground(new Color(174,71,213));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String usuario=jTextFieldUsuario.getText();
        String contra=new String(jPasswordFieldContra.getPassword());
        
        if(usuario.equals("") || usuario == null || contra.equals("") ||contra == null || usuario.equals("Inserta tu usuario") || contra.equals("INSERTAR")) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacíos", "Campos vacíos", JOptionPane.ERROR_MESSAGE);
        } else {
            // El usuario da datos válidos. Se abre la interfaz
            if(esUsuario(usuario)) {
                PantallaSegunda p=new PantallaSegunda();
                p.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(this, "El usuario solo puede contener letras, nada de números ni espacios en blanco", "Usuario no válido", JOptionPane.ERROR_MESSAGE);    
            }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    // Método para verificar que el usuario solo contiene letras
    private boolean esUsuario(String usuario) {
        return usuario.matches("[a-zA-Z]+");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonEntrar;
    private javax.swing.JPanel ContenedorGeneral;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private jpanelimagen.JPanelImagen jPanelImagenLogo;
    private javax.swing.JPasswordField jPasswordFieldContra;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
