/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegosdialogs;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author PROGRAMACION
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        SombraTitulo = new javax.swing.JLabel();
        BotonJugar = new javax.swing.JPanel();
        jLabelJugar = new javax.swing.JLabel();
        FondoAjedrez = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Harrington", 1, 60)); // NOI18N
        Titulo.setForeground(new java.awt.Color(48, 61, 40));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Ajedrez");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 70));

        SombraTitulo.setFont(new java.awt.Font("Harrington", 1, 60)); // NOI18N
        SombraTitulo.setForeground(new java.awt.Color(91, 117, 76));
        SombraTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SombraTitulo.setText("Ajedrez");
        jPanel1.add(SombraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 400, 70));

        BotonJugar.setBackground(new java.awt.Color(71, 90, 51));
        BotonJugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 223, 197), 2));
        BotonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelJugar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelJugar.setForeground(new java.awt.Color(204, 223, 197));
        jLabelJugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJugar.setText("JUGAR");
        jLabelJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelJugarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonJugarLayout = new javax.swing.GroupLayout(BotonJugar);
        BotonJugar.setLayout(BotonJugarLayout);
        BotonJugarLayout.setHorizontalGroup(
            BotonJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        BotonJugarLayout.setVerticalGroup(
            BotonJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelJugar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jPanel1.add(BotonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 132, 138, 68));

        FondoAjedrez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juegosdialogs/images/tablero.png"))); // NOI18N
        jPanel1.add(FondoAjedrez, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugarMouseClicked
        String nombre=JOptionPane.showInputDialog(this, "Inserta tu nombre",null);
        
        if(nombre!=null && !nombre.trim().isEmpty()) {
            // Le paso el parámetro nomber para poder utilizarlo en el Dialog
            EscogerPersonaje dialog=new EscogerPersonaje(this, true, nombre);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jLabelJugarMouseClicked

    private void jLabelJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugarMouseEntered
        BotonJugar.setBackground(new Color(71,75,56));
    }//GEN-LAST:event_jLabelJugarMouseEntered

    private void jLabelJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugarMouseExited
        BotonJugar.setBackground(new Color(71,90,51));
    }//GEN-LAST:event_jLabelJugarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonJugar;
    private javax.swing.JLabel FondoAjedrez;
    private javax.swing.JLabel SombraTitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelJugar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
